### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by tarciozemel** [addyosmani/critical#108]
Trying to test the plugin, but I always get this error:

``` js
Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at module.exports (/var/www/node_modules/penthouse/lib/index.js:32:10)
    at tryCatcher (/var/www/node_modules/bluebird/js/main/util.js:26:23)
    at ret (eval at <anonymous> (/var/www/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /var/www/node_modules/critical/lib/core.js:166:20
    at tryCatcher (/var/www/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/www/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/var/www/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/www/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Tried to find some generic fix and follow many community suggestions -- as update Node and use manual instalation of PhantomJS --, but still not.

**Comment by addyosmani** [comment]
Have you tried https://docs.npmjs.com/getting-started/fixing-npm-permissions?

**Comment by tarciozemel** [comment]
Just tried and still nothing.  =/

PS: I'm in a Vagrant environment, but all the other gulp tasks are OK, so I presume this is not influencing in nothing.

**Comment by bezoerb** [comment]
@tarciozemel: Any updates on this one?

**Comment by bezoerb** [comment]
Closing this due to inactivity. Seems fixed after all ;)
