### ISSUE TITLE
Receiving an event emitter memory leak

### ISSUE THREAD

**Issue by micahblu** [addyosmani/critical#121]
I have 0.6.0, when running the gulp task I get:

```
[11:31:26] Starting 'critical'...
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.EventEmitter.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:769:26)
    at module.exports (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/penthouse/lib/index.js:77:13)
    at tryCatcher (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/util.js:26:23)
    at ret (eval at <anonymous> (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:12:39)
    at /home/micah/Projects/wirecashwebsite/node_modules/critical/lib/core.js:166:20
    at tryCatcher (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/micah/Projects/wirecashwebsite/node_modules/critical/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
```

My gulp task:

```js
var critical = require('critical').stream;

// Generate & Inline Critical-path CSS
gulp.task('critical', function() {
	return gulp.src('dist/*.html')
  	.pipe(critical({base: 'dist/', inline: true, css: ['dist/assets/stylesheets/main.css']}))
    .pipe(gulp.dest('dist'));
});
```

**Comment by micahblu** [comment]
I upgraded to the latest version of node v5.4.1 and still the issue however the error trace is a bit different:

```
(node) warning: possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at module.exports (/home/micah/Projects/wirecashwebsite/node_modules/penthouse/lib/index.js:77:13)
    at tryCatcher (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/util.js:26:23)
    at ret (eval at <anonymous> (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /home/micah/Projects/wirecashwebsite/node_modules/critical/lib/core.js:166:20
    at tryCatcher (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/micah/Projects/wirecashwebsite/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by pocketjoso** [comment]
You could always add `process.setMaxListeners(0)` in your code, which will mute this warning.

Not sure why `critical` itself is leaking though.

**Comment by bezoerb** [comment]
@micahblu could you test against the `master` or `vinyl` branch? I Think this could be related to the recently fixed memory leaks in penthouse. I just tested gulp + critical on a folder with 36 files and got no memory leak warnings. So i guess this is should already be fixed.

**Comment by micahblu** [comment]
@bezoerb I'm going to close this for now as it only appears to be happening on my ubuntu machine? I've tried the task on several other machines and was unable to recreate the issue. Thanks for the quick reply.
