### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#14]
```

> critical@0.1.3 test C:\Users\xmr\Desktop\critical
> mocha test.js --timeout 15000

\
....|

  2 passing (2s)
  6 failing

  1)  generates critical-path CSS successfully:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:33:9
      at C:\Users\xmr\Desktop\critical\index.js:60:15
      at C:\Users\xmr\Desktop\critical\node_modules\mocha\node_modules\glob\node_modules\graceful-fs\graceful-fs.js:104:5
      at Object.oncomplete (fs.js:107:15)

  2)  generates minified critical-path CSS successfully:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:47:9
      at C:\Users\xmr\Desktop\critical\index.js:63:13
      at ChildProcess.<anonymous> (C:\Users\xmr\Desktop\critical\node_modules\penthouse\lib\index.js:43:13)
      at ChildProcess.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:809:12)

  3)  generates critical-path CSS without writing to disk:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:60:9
      at C:\Users\xmr\Desktop\critical\index.js:63:13
      at ChildProcess.<anonymous> (C:\Users\xmr\Desktop\critical\node_modules\penthouse\lib\index.js:43:13)
      at ChildProcess.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:809:12)

  4)  inlines critical-path CSS successfully:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:72:9
      at C:\Users\xmr\Desktop\critical\index.js:92:9
      at C:\Users\xmr\Desktop\critical\node_modules\mocha\node_modules\glob\node_modules\graceful-fs\graceful-fs.js:104:5
      at Object.oncomplete (fs.js:107:15)

  5)  inlines critical-path CSS without writing to disk:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:83:9
      at C:\Users\xmr\Desktop\critical\index.js:95:9
      at fs.js:271:14
      at C:\Users\xmr\Desktop\critical\node_modules\mocha\node_modules\glob\node_modules\graceful-fs\graceful-fs.js:104:5
      at Object.oncomplete (fs.js:107:15)

  6)  inlines and minified critical-path CSS:
     Uncaught AssertionError: false == true
      at C:\Users\xmr\Desktop\critical\test.js:96:9
      at C:\Users\xmr\Desktop\critical\index.js:92:9
      at C:\Users\xmr\Desktop\critical\node_modules\mocha\node_modules\glob\node_modules\graceful-fs\graceful-fs.js:104:5
      at Object.oncomplete (fs.js:107:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

I managed to fix one of the tests by forcing LF. 5 still fail though.

**Comment by bezoerb** [comment]
Tests still green on windows. Closing this for now.
