### ISSUE TITLE
Critical not works if url contains "-"

### ISSUE THREAD

**Issue by amorphine** [addyosmani/critical#173]
Here are my gulp tasks 

```
var settings = {
    base_url: "https://digitec.ru/",
    dest_folder: "css/critical/",
    dimensions: [
                    {prefix:'', width: 1920, height: 1080 },
                    {prefix:'mobile', width: 360, height: 640 }
                ],
    urls : [
        {name: "ProductProduct", url:"philips-xenium-e160-black-133619.html"},
        //{name: "CommonHome", url:""},
        //{name: "", url:""},
        //{name: "", url:""},
    ]
};

module.exports = settings;
```

```
module.exports = function(gulp, plugins) {
    return function () {
        var critical = require('critical'),
            settings = require("./settings.js"),
            urls = settings.urls,
            dimensions = settings.dimensions;

        dimensions.forEach(function(dimension){
            urls.forEach(function(entry){
                critical.generate({
                    src: settings.base_url + entry.url,
                    dest: settings.dest_folder + dimension.prefix + entry.name + '.css',
                    minify: true,
                    ignore: ['.big-header-wrapper', 'header.small'],
                    timeout: 10000,
                    width: dimension.width,
                    height: dimension.height
                });
            });
        });
    };
}
```

If url contains simbol '-' result of script is empty. Another symptom is that if I run it for local site 'digitec.local' I get 500 error:

```
Unhandled rejection Error: Wrong status code 500 for http://digitec.local/philips-xenium-e160-black-133619.html
    at Request._callback (/var/www/digitec/node_modules/critical/lib/file-helper.js:95:31)
    at Request.self.callback (/var/www/digitec/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/www/digitec/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/www/digitec/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Unhandled rejection Error: Wrong status code 500 for http://digitec.local/philips-xenium-e160-black-133619.html
    at Request._callback (/var/www/digitec/node_modules/critical/lib/file-helper.js:95:31)
    at Request.self.callback (/var/www/digitec/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/www/digitec/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/www/digitec/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

But apache logs show no errors

**Comment by LordRembo** [comment]
@amorphine  I'm having a similar issue. I have a url containing a '-' that is giving me the same 500 error when Gulp tries to run critical. Did you find a solution for this?
