### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by geosenna** [addyosmani/critical#233]
Since I update critical to 0.9.0 from 0.7.0 I get this error when I launch the critical function. It was working fine before, nothing has change except the version update.
Is anyone already have this issue?

**Comment by pocketjoso** [comment]
What `node` version are you on?
Since `penthouse` started using generators, support for node version below `4` was dropped. Perhaps this is your issue?

**Comment by geosenna** [comment]
node -v => 4.2.3

**Comment by pocketjoso** [comment]
Could you update to a newer node version and test - 7 perhaps?

If it still fails something has gone wrong during the installation, if so I would try removing critical (yarn/npm remove critical) and re-adding it.

**Comment by geosenna** [comment]
I already try to remove it and add it again, without success.
My solution is very heavy and doesn't support any update of node for now...
Maybe there is way to add "regenerator-runtime/runtime" manually?

**Comment by pocketjoso** [comment]
Sure, just npm install or yarn add it.

**Comment by geosenna** [comment]
By adding it manually the error is gone, but other errors appears... 
Is critical ready to be use with Gulp 4? And are you sure node 4 is the minimum version to have?

**Comment by pocketjoso** [comment]
Can you please paste the errors here?

It could also be worthwhile to remove and re-install all the node_modules, especially if you're using `npm` (and not `yarn`), as they can get into a corrupted state sometimes: `rm -rf node_modules && npm install`

**Comment by geosenna** [comment]
`Unhandled rejection TypeError: this is not a typed array.
    at Function.from (native)
    at C:\projects\mb\trunk\FrontCode\node_modules\critical\lib\file-helper.js:77:38
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:78:10)
    at bound (domain.js:280:14)
    at MappingPromiseArray.runBound (domain.js:293:12)
    at Promise._settlePromise (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\map.js:101:18)
    at MappingPromiseArray.PromiseArray._iterate (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:78:10)
    at bound (domain.js:280:14)
    at MappingPromiseArray.runBound (domain.js:293:12)
    at Promise._settlePromise (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\map.js:101:18)
    at Promise._settlePromise (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\projects\mb\trunk\FrontCode\node_modules\bluebird\js\release\promise.js:614:10)`

**Comment by geosenna** [comment]
I update node from 4.2.4 to 4.8.0 with nvm and this is working now. Many thanks for the help @pocketjoso  :)
Perhaps "node": ">=4.0" in package.json should be updated, or maybe the issue was coming from myself with some corrupted repo...

**Comment by pocketjoso** [comment]
Thanks for the feedback, will investigate.
