### ISSUE TITLE
I have a trouble with extract option

### ISSUE THREAD

**Issue by DanchMax** [addyosmani/critical#239]
Hi!

I have a trouble with extract option, when inline is turend on

Here is my simple code:

```
var gulp = require('gulp');
//var gutil = require('gulp-util');
var critical = require('critical');

gulp.task('critical', function (cb) {
    critical.generate({
    base: 'dist/test/',
	inline: true,
    src: 'charo.html',
     dest: './new/critical.css',
		width: 320,
		height: 480,
		
    extract: true,
    minify: true
	},
	function(err, output) { cb(err);})

});
```

I'm getting such errors:

```
PS E:\myproject> gulp critical
[15:13:42] Using gulpfile E:\myproject\gulpfile.js
[15:13:42] Starting 'critical'...
[15:13:53] 'critical' errored after 11 s
[15:13:53] Error: undefined:1972:7: property missing ':'
    at error (E:\myproject\node_modules\css\lib\parse\index.js:62:15)
    at declaration (E:\myproject\node_modules\css\lib\parse\index.js:223:33)
    at declarations (E:\myproject\node_modules\css\lib\parse\index.js:252:19)
    at rule (E:\myproject\node_modules\css\lib\parse\index.js:560:21)
    at rules (E:\myproject\node_modules\css\lib\parse\index.js:117:70)
    at stylesheet (E:\myproject\node_modules\css\lib\parse\index.js:81:21)
    at Object.module.exports [as parse] (E:\myproject\node_modules\css\lib\parse\index.js:564:20)
    at api (E:\myproject\node_modules\cave\src\cave.js:8:19)
    at Object.<anonymous> (E:\myproject\node_modules\inline-critical\index.js:136:51)
    at initialize.exports.each (E:\myproject\node_modules\cheerio\lib\api\traversing.js:300:24)
    at module.exports (E:\myproject\node_modules\inline-critical\index.js:124:18)
    at Bluebird.props.then.result (E:\myproject\node_modules\critical\index.js:107:20)
    at tryCatcher (E:\myproject\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\myproject\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\myproject\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\myproject\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\myproject\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\myproject\node_modules\bluebird\js\release\promise.js:638:18)
    at PropertiesPromiseArray.PromiseArray._resolve (E:\myproject\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PropertiesPromiseArray._promiseFulfilled (E:\myproject\node_modules\bluebird\js\release\props.js:78:14)
    at Promise._settlePromise (E:\myproject\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (E:\myproject\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\myproject\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\myproject\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (E:\myproject\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (E:\myproject\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (E:\myproject\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\myproject\node_modules\bluebird\js\release\promise.js:614:10)
```

If I commets //inline:true, css file is forming ok.

**Comment by bezoerb** [comment]
Looks like some syntax error inside the css. 
With `extract: true` the css is parsed to remove the critical css. This step fails. 
@DanchMax: Could you check the css?

**Comment by DanchMax** [comment]
Yes it.s realy was problem with css, tahks for quickly answer
