### ISSUE TITLE
toString() errors and more.

### ISSUE THREAD

**Issue by micahblu** [addyosmani/critical#44]
Getting toString() errors on two lines, 138 and 219 in index.js

```bash
/Library/WebServer/Documents/WireCash-website/node_modules/critical/node_modules/bluebird/js/main/async.js:95
                throw res.e;
                         ^
TypeError: Cannot call method 'toString' of undefined
    at /Library/WebServer/Documents/WireCash-website/node_modules/critical/index.js:138:30
```

and once I removed the method on 138 I got the same for 219:

```bash
/Library/WebServer/Documents/WireCash-website/node_modules/critical/node_modules/bluebird/js/main/async.js:95
                throw res.e;
                         ^
TypeError: Cannot call method 'toString' of undefined
    at /Library/WebServer/Documents/WireCash-website/node_modules/critical/index.js:219:28
```
Removing toString() from 219, got rid of the error messages, however I'm not getting inlined critical css at all?

My Gulp configuration is below and this is with the latest 0.4.0 release of critical. I'll do some investigating on my end, but wanted to bring attention to the issue.

```javascript

var gulp = require('gulp'),
    critical = require('critical'),
    fs = require('fs');


// Generate & Inline Critical-path CSS
gulp.task('critical', function () {

    critical.generateInline({
        base: 'dist/',
        src: 'index.html',
        cssPath: 'stylesheets/',
        styleTarget: 'stylesheets/critical.css',
        htmlTarget: 'index.html',
        width: 320,
        height: 480,
        minify: true,
        maxInlineImageSize: 10240
    });
    critical.generateInline({
        base: 'dist/',
        src: 'about.html',
        cssPath: 'stylesheets/',
        styleTarget: 'stylesheets/critical.css',
        htmlTarget: 'about.html',
        width: 320,
        height: 480,
        minify: true,
        maxInlineImageSize: 10240
    });
});
```

**Comment by bezoerb** [comment]
Closing as this should be fixed by now. 
Feel free to re-open if there's still something we didn't consider yet.
