### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by archy-bold** [addyosmani/critical#451]
> /home/simon/Development/selectfashion/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
>      } catch {
>              ^
>
>SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/simon/Development/selectfashion/node_modules/fs-extra/lib/mkdirs/index.js:3:44)                                                                                                  

I'm trying to run the latest version (2.0.0-26) and getting the above error. According to this issue on another repo (https://github.com/vercel/pkg/issues/883), it's related to the latest version of fs-extra and it should be downgraded to 8.1.0.

**Comment by bezoerb** [comment]
@archy-bold: I've removed the fs-extra dependency in v2.0.0-27. Could you try again?

**Comment by archy-bold** [comment]
That fixed that particular issue, but now I'm seeing the following error in `asset-resolver`. Is that something to do with my version of node?

```
/home/simon/Development/selectfashion/node_modules/asset-resolver/node_modules/got/dist/source/create.js:133
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/simon/Development/selectfashion/node_modules/asset-resolver/node_modules/got/dist/source/index.js:7:18)
```

**Comment by bezoerb** [comment]
Which version of node are you using?

**Comment by archy-bold** [comment]
Node version is 8.10.0

**Comment by bezoerb** [comment]
This is strange... you should not be able to install critical@next with this version of node:
https://github.com/addyosmani/critical/blob/master/package.json#L26

**Comment by archy-bold** [comment]
I upgraded to node 12 and all is good now. Odd I didn't even get a warning.
