### ISSUE TITLE
Dies on 404 when traversing path

### ISSUE THREAD

**Issue by zabugin-oleg** [addyosmani/critical#455]
Hey!

I used to use critical 1.x before without problem. Not I'm trying to use critical 2 and I'm facing a problem I don't really know how to solve. 

The problem is:
I use URL as "src". URL is http://localhost/foo/bar. The problem is that critical tries to access **http://localhost/foo** too, but there is no such page and the response is 404. After this critical dies with this error:

[15:24:29] Using gulpfile ~/dev/trivia/templates/fomantic/gulpfile.js
[15:24:29] Starting 'criticalcss'...
[15:24:35] 'criticalcss' errored after 6.47 s
[15:24:35] RequestError: Parse Error: Expected HTTP/
    at ClientRequest.<anonymous> ([...]/fomantic/node_modules/got/dist/source/core/index.js:826:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at ClientRequest.origin.emit ([...]/fomantic/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnData (_http_client.js:514:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:547:15)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.socketOnData (_http_client.js:507:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:547:15)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

Critical config is:
critical.generate({
		src: criticalSrc,
		target: criticalDest,
		inline: false,
		minify: true,
		extract: true,
		dimensions: [{
				height: 900,
				width: 1200
			},{
				height: 812,
				width: 375
			}
		],
		ignore: ['@font-face'],
		penthouse: {'forceInclude': [/cc-/]},
		assetPaths: ['/static/']
	}, function(err, output){
		if (err) {
			console.log(element.url)
			console.log(err);
			console.log('---');
		}
		callback();
	});

**Comment by bezoerb** [comment]
Hey @zabugin-oleg 
It looks like critical is  trying to fetch some resources in http://localhost/foo. Are there any stylesheets or images referenced to this url in the html?

Can you  set the `DEBUG` environment variable to `critical:*`, try again and post the output?
Maybe you could also pass the path to your css to critical so it doesn't need to resolve the files?

BTW: How is it possible that /foo/bar exists and /foo doesn't?

**Comment by bezoerb** [comment]
closing this due to lack of feedback.
Feel free to re-open if there are any new insights to add here
