### ISSUE TITLE
RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by QuentinCurtet** [addyosmani/critical#460]
Hello,

I'm using my own certificate authority.
Using critical@1.3.10 on Debian9, all worked correctly.
But using critical@2.0.1, i got the following error : 
`RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (./node_modules/critical/node_modules/got/dist/source/core/index.js:891:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (./node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:506:15)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:120:14)`

So, is it possible to configure got (the package) through critical ? If yes, how ?

Or, how is it possible to configure the path to my own certificate authority to make it work like before ?

Thanks in advance.

**Comment by bezoerb** [comment]
Hey @QuentinCurtet, I think you can your the request option to configure got.

**Comment by QuentinCurtet** [comment]
@bezoerb I'm not sure to understand your answer
You suggest me to install got and make the request myself ?

**Comment by bezoerb** [comment]
ah, no... there's an undocumented option.
```js
critical.generate({
   request: { /* got options */  },
   ...
})

See: https://github.com/addyosmani/critical/blob/master/src/config.js#L42 and https://github.com/addyosmani/critical/blob/master/src/file.js#L310

**Comment by QuentinCurtet** [comment]
@bezoerb Can you majke a pull request to document it please ?
It works perfectly for me by the way thank you :)
