### ISSUE TITLE
Dest displaying as not allowed and base option of critical not being recognized

### ISSUE THREAD

**Issue by daecepi** [addyosmani/critical#468]
Hello
I have a recent error while implementing critical in a lando instance.
- Critical: 2.0.4
- Node: 10.22.0
- Lando: v3.0.9
- Gulp: CLI version: 2.3.0 Local version: 4.0.2

Specific error:
```
(node:4903) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/penthouse/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

at onClose (/app/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:750:14)
at Interface.helper.addEventListener (/app/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:739:50)
at Interface.emit (events.js:203:15)
at Interface.EventEmitter.emit (domain.js:466:23)
at Interface.close (readline.js:397:8)
at Socket.onend (readline.js:173:10)
at Socket.emit (events.js:203:15)
at Socket.EventEmitter.emit (domain.js:466:23)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
Checkedthe troubleshooting page but mentions a node upgrade but even with the version 12 recommended at least the error still appears.
```

Also the error was present after following this give, the code implemented is the one there:

https://nystudio107.com/blog/implementing-critical-css
https://nystudio107.com/blog/a-better-package-json-for-the-frontend

Thanks in advance.

**Comment by bezoerb** [comment]
> error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
@daecepi: The error message points out that there are some required dependencies missing on your system.

Read more  Puppeteer's [troubleshooting section](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix).
