### ISSUE TITLE
Error: Could not parse CSS stylesheet

### ISSUE THREAD

**Issue by Bryan988** [addyosmani/critical#516]
### Error message 
```
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (C:\wamp64\www\httpcs\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:34:21)
    at HTMLStyleElementImpl._updateAStyleBlock (C:\wamp64\www\httpcs\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:68:5)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (C:\wamp64\www\httpcs\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:42:10)
    at OpenElementStack.pop (C:\wamp64\www\httpcs\node_modules\jsdom\lib\jsdom\browser\parser\html.js:44:12)
    at Object.endTagInText [as END_TAG_TOKEN] (C:\wamp64\www\httpcs\node_modules\parse5\lib\parser\index.js:2153:20)
    at Parser._processToken (C:\wamp64\www\httpcs\node_modules\parse5\lib\parser\index.js:657:55)
    at Parser._processInputToken (C:\wamp64\www\httpcs\node_modules\parse5\lib\parser\index.js:684:18)
    at Parser._runParsingLoop (C:\wamp64\www\httpcs\node_modules\parse5\lib\parser\index.js:440:18)
    at Parser.parse (C:\wamp64\www\httpcs\node_modules\parse5\lib\parser\index.js:344:14)
    at Object.parse (C:\wamp64\www\httpcs\node_modules\parse5\lib\index.js:10:19) {{ source('critical/layout.critical.css') }}
```

### Source of error

As you may have notice, the {{ source('critical/layout.critical.css') }} is triggering the error. 
Why is it there ? 
As I am using twig for the rendering of the page, after generating the critical css for the page "layout", I included what was generated from the package "critical" thanks to [this function](https://twig.symfony.com/doc/2.x/functions/source.html). 
In order to be interpreted, I had to place it between <style> tag. 
To sum up  this is what i did : 
- Generate critical css
- Include critical css with "source"

It looks like that in the code 
![image](https://user-images.githubusercontent.com/55983043/131628125-8bee7997-1031-45e3-a12c-bf229ee81d25.png)

Once this is done, I load in async the rest of the css using WebPack Encore
![image](https://user-images.githubusercontent.com/55983043/131636239-8418696b-7c8d-4eb8-8bd9-98723b0a7d1a.png)

It also throw me an error when i print the callback of generate : 

``` 
Error: Error: file "{{ entry }}" not found in "..\..\css\critical". Specify base path.
    at C:\wamp64\www\httpcs\node_modules\inline-critical\index.js:175:17
    at Array.map (<anonymous>)
    at inline (C:\wamp64\www\httpcs\node_modules\inline-critical\index.js:158:11)
    at create (C:\wamp64\www\httpcs\node_modules\critical\src\core.js:222:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.generate (C:\wamp64\www\httpcs\node_modules\critical\index.js:23:20)
```

### What I looked  for

I have try to go through the documentation of both [critical ](https://github.com/addyosmani/critical) and [penthouse](https://github.com/pocketjoso/penthouse/tree/master), but I did not found anything to "ignore" an include or a function like i'm using. As it is between style tag, critical must try to interpret it and I can not ignore it. Is there a way to prevent the function from throwing an error ? 

Thanks for your replies !

**Comment by bezoerb** [comment]
Hey @Bryan988,
Twig isn't supported as well as other templating engines. 
See #318 #362 #94 #199

You will need to compile your templates first and run critical on the html result
