### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by devtombiz** [addyosmani/critical#575]
Hi all,
I am trying to use critical to optimize a site pages. I have about 2K static pages.
It works very well for the first page and a few other, but unfortunately, after a few pages it crashes with this error:
(It does not always crash on the same page)

```
  critical:core Call penthouse with: {
  forceInclude: [],
  timeout: 30000,
  maxEmbeddedBase64Length: 10240,
  cssString: '/* Vehicle ... dth:73vw}}',
  url: 'file:///private/var/folders/bw/3g_yz02n4_q_x8b9xvjpm9bw0000gn/T/f67c88ea752aad90832e52bd7d540de5/5c11cf334447419172c786712dc28f70.html',
  width: 500,
  height: 694
} +2s
Error processing dist/winstonsalem-nc-754/index.html: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

Processing dist/winstonsalem-nc-1407/index.html...
  critical:config {
  critical:config   base: 'dist/',
  critical:config   src: 'index.html',
  critical:config   target: { css: 'critical.css', uncritical: 'uncritical.css' },
  critical:config   dimensions: [
  critical:config     { height: 694, width: 500 },
  critical:config     { height: 1023, width: 500 },
  critical:config     { width: 1600, height: 900 }
  critical:config   ],
  critical:config   inline: { basePath: 'dist/', strategy: 'media' },
  critical:config   concurrency: 1,
  critical:config   strict: false,
  critical:config   ignoreInlinedStyles: false,
  critical:config   extract: true,
  critical:config   inlineImages: false,
  critical:config   width: 1300,
  critical:config   height: 900,
  critical:config   maxImageFileSize: 10240,
  critical:config   include: [],
  critical:config   penthouse: { forceInclude: [], timeout: 30000, maxEmbeddedBase64Length: 10240 }
  critical:config } +386ms
/Users/thomas/Dev/rseo/rseo-sl-wafflehouse/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:750
      reject(new Error([
             ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/thomas/Dev/rseo/rseo-sl-wafflehouse/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/Users/thomas/Dev/rseo/rseo-sl-wafflehouse/node_modules/penthouse/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (node:events:526:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.7.0
```

It seems obvious that the issue is more with puppeteer (or penthouse?) than critical, but did you already had this ? any idea of things I should try as a workaround...or a fix ?

Thank you!
-Thomas

**Comment by devtombiz** [comment]
OK, I have found another solution: creating and configuring a local puppeteer instance and passing all that to penthouse via critical:

```
async function findCriticalCss(htmlFile, browser, retryCount = 0) {
  return new Promise((resolve) => {
    gulp
      .src(htmlFile)
      .pipe(
        critical({
          base: "dist/",
          inline: true,
          target: {
            css: "critical.css",
            uncritical: "uncritical.css",
          },
          dimensions: [
            { height: 694, width: 500 },
            { width: 1600, height: 900 },
          ],
          concurrency: 1,
          penthouse: {
            browser: browser,
            timeout: 30000,
            unstableKeepBrowserAlive: true,
          },
        })
      )
      .on("error", async (err) => {
        console.log(`Error in ${htmlFile}: ${err}`);
        if (retryCount < 3) {
          console.log(`Retrying ${htmlFile}...`);
          await processFile(htmlFile, browser, retryCount + 1);
        }
        resolve(); // Always resolve to continue with the next file
      })
      .pipe(gulp.dest("dist"))
      .on("end", () => {
        console.log(`Processed ${htmlFile}`);
        resolve();
      });
  });
}

gulp.task("criticalCss", async function () {
  const htmlFiles = glob.sync("dist/**/index.html").sort();
  console.log("Finding critical CSS in all index.html files:");

  const browser = await puppeteer.launch({
    headless: "new",
    defaultViewport: null,
    args: [
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-first-run",
      "--no-sandbox",
      "--no-zygote",
      "--single-process",
    ],
  });

  for (const htmlFile of htmlFiles) {
    await findCriticalCss(htmlFile, browser);
  }

  console.log("All files processed.");
});
```

**Comment by bezoerb** [comment]
🚀
